### ISSUE TITLE
Fronted main screen implementation

### ISSUE THREAD

**Issue by dawba** [dawba/ch4t#7]
Using the skeleton of the main frontend directory we need to start to implement the base of our app.

The good way to start it would to be make a list of required components and then we can split our attention/work to them.

Try to define what is needed based on our figma designs - and then we can get to work and assign certain tasks to each other.

**Comment by Admswj** [comment]
- Components
  - [ ] **SideMenu** // leftmost panel in chat view
    - [ ] **NavigationButton** // (direct chats, group chats, new chat and settings)
  - [ ] **ExtendedMenu** // panel shown by interactions with side menu <— wrapper populated by the following 4:
   
    - [ ] **GroupChatsList**
      - [ ] **ChatTile** // stateful tile with basic information about a particular chat
      - [ ] **Search** // customised search bar <— components shared by both lists
    - [ ] **ChatCreationPanel**
      - [ ] **CircularImage** // allows to upload a picture and has a placeholder, can be also used alongside chat tiles with interactions disabled
    - [ ] **SettingPanel**
      - [ ] **ColourPicker** // probably we will use an open source one
  - [ ] **ChatView** // wrapper for rightmost view 
    - [ ] **AttachButton** // button allowing to upload assets from computer ( I propose to ask for permissions at the site load and then eventually disable it)
    - [ ] **CustomTextField** // we shall address an aspect of it extending on more text inserted for example
    - [ ] **Emoticons ???** // Uncertain if this component is included
    - [ ] **SendButton** // simply a button to send a message
    - [ ] **MessageBubble** // basically an UI equivalent of a message

- Screens
  - [ ] **LoginScreen**
  - [ ] **ChatScreen**

Designs will be completed soon...

**Comment by dawba** [comment]
DONE!
